\c abyarsanat
\i 1.log.sql
\i 2.file.sql
\i 3.admin.sql
\i 4.page.sql
\i 5.blog_category.sql
\i 6.blog_tag.sql
\i 7.blog.sql
\i 8.product_brand.sql
\i 9.product_category.sql
\i 10.product_guaranty.sql
\i 11.product_insurance.sql
\i 12.product_category_filter.sql
\i 13.product_category_filter_value.sql
\i 14.product.sql
\i 15.product_model.sql
\i 16.product_relations.sql
\i 17.user.sql
\i 18.promotion.sql
\i 18.special.sql